// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 30.08.2024, 00:16:20
const configMerger = require("/home/sebastian/VSC/tripFinder/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/home/sebastian/VSC/tripFinder/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/sebastian/VSC/tripFinder/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/sebastian/VSC/tripFinder/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/sebastian/VSC/tripFinder/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/sebastian/VSC/tripFinder/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/sebastian/VSC/tripFinder/plugins/**/*.{js,ts,mjs}","/home/sebastian/VSC/tripFinder/composables/**/*.{js,ts,mjs}","/home/sebastian/VSC/tripFinder/utils/**/*.{js,ts,mjs}","/home/sebastian/VSC/tripFinder/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/sebastian/VSC/tripFinder/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/sebastian/VSC/tripFinder/app.config.{js,ts,mjs}"] }));

module.exports = config
